name: Tests
"on":
  pull_request: {}
  push:
    branches:
    - main
jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: "18.x"
        cache: 'npm'
    - name: Run Install
      run: npm ci
    - name: Run Build
      run: npm run build --if-present
    - name: Run Tests
      run: npm test
    - name: Report coverage
      run: bash <(curl -s https://codecov.io/bash)
