name: Tests
"on":
  pull_request: {}
  push:
    branches:
    - main
jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - uses: actions/setup-node@v2
      with:
        node-version: "14.x"
    - name: Run Install
      run: npm ci
    - name: Run Build
      run: npm build
    - name: Run Tests
      run: npm test
    - name: Report coverage
      run: bash <(curl -s https://codecov.io/bash)
